from pathlib import Path
from datetime import datetime


class ReportGenerator:

    def progress_bar(self, score):

        filled = int(score / 5)

        return "█" * filled + "░" * (20 - filled)

    def generate(self, result, page_name):

        reports = Path("reports")
        reports.mkdir(exist_ok=True)

        score = result["compliance_score"]

        if score >= 90:
            color = "#2ecc71"
            status = "PASS"

        elif score >= 70:
            color = "#f39c12"
            status = "WARNING"

        else:
            color = "#e74c3c"
            status = "FAIL"

        html = f"""

<!DOCTYPE html>

<html>

<head>

<title>Compliance Report</title>

<style>

body{{
background:#eef2f7;
font-family:Arial;
padding:40px;
}}

.container{{
background:white;
max-width:1100px;
margin:auto;
padding:40px;
border-radius:12px;
box-shadow:0 0 20px rgba(0,0,0,.15);
}}

.header{{
text-align:center;
margin-bottom:30px;
}}

.score{{
font-size:60px;
font-weight:bold;
color:{color};
}}

.bar{{
font-size:28px;
margin-bottom:20px;
}}

.card{{
background:#fafafa;
padding:20px;
margin-top:20px;
border-radius:10px;
border-left:6px solid {color};
}}

li{{
padding:8px;
}}

.footer{{
margin-top:40px;
text-align:center;
color:gray;
}}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>AI Documentation Compliance Report</h1>

<p><b>Generated:</b>
{datetime.now().strftime("%d %B %Y %H:%M")}</p>

</div>

<div class="score">

{score}%

</div>

<div class="bar">

{self.progress_bar(score)}

</div>

<h2>Status : {status}</h2>

<hr>

<h2>Page</h2>

<p>{page_name}</p>

<div class="card">

<h2>Matched Elements</h2>

<ul>

{"".join(f"<li>✅ {i}</li>" for i in result["matched"])}

</ul>

</div>

<div class="card">

<h2>Missing Elements</h2>

<ul>

{"".join(f"<li>❌ {i}</li>" for i in result["missing"])}

</ul>

</div>

<div class="card">

<h2>Extra Elements</h2>

<ul>

{"".join(f"<li>⚠ {i}</li>" for i in result["extra"])}

</ul>

</div>

<div class="card">

<h2>AI Recommendation</h2>

<p>

{result["summary"]}

</p>

</div>

<div class="footer">

Generated by

<h3>AI Documentation Compliance Agent</h3>

</div>

</div>

</body>

</html>

"""

        filename = reports / f"{page_name.lower().replace(' ','_')}.html"

        with open(filename, "w", encoding="utf-8") as file:
            file.write(html)

        return filename